# Generated by Django 5.1.2 on 2024-11-07 18:40

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[(orders.models.DeliveryType['IMMEDIATE'], 'immediate'), (orders.models.DeliveryType['SCHEDULED'], 'scheduled')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[(orders.models.OrderType['DELIVERY'], 'delivery'), (orders.models.OrderType['PICKUP'], 'pickup')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(orders.models.OrderStatus['PROCESSING'], 'processing'), (orders.models.OrderStatus['PREPARING'], 'preparing'), (orders.models.OrderStatus['DELIVERING'], 'delivering'), (orders.models.OrderStatus['DELIVERED'], 'delivered'), (orders.models.OrderStatus['CANCELED'], 'canceled')], default='processing', max_length=20),
        ),
    ]
